spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to eazybank accounts related Production APIs"
  contactDetails:
    name: "Shaishav Parekh - Production Team"
    email: "shaishav_prod@gmail.com"

  OnCallSupport:
    - (777) 777-123
    - (777) 773-1234

