spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to eazybank accounts related QA APIs"
  contactDetails:
    name: "Shaishav Parekh -QA Support"
    email: "shaishavparekh23@gmail.com"

  OnCallSupport:
    - (666) 666-123
    - (666) 663-1234

